import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import TanStackProvider from '@/components/TanStackProvider/TanStackProvider';
import Header from '@/components/Header/Header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TanStackProvider>
          {/* <Header /> НЕ ЗАБУДЬ УБРАТЬ КОМЕНТИРОВАНИЕ ХЕДЕРА (ВРЕМЕННАЯ ЗАГЛУШКА ЧТОБЫ ВИДЕТЬ РЕНДЕР ФОРМЫ РЕГИСТРАЦИИ), после мита поняли что тут проблема и нужно убрать этот хедер - ЕГО МОЖНО УДАЛИТЬ*/}
          {children}
        </TanStackProvider>
      </body>
    </html>
  );
}
